default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cost_splitter_api_development

test:
  <<: *default
  database: cost_splitter_api_test

production:
  <<: *default
  database: cost_splitter_api_production
  username: cost_splitter_api
  password: <%= ENV['COST_SPLITTER_API_DATABASE_PASSWORD'] %>
